import { ref } from "vue";

export const columns = [
  {
    label: "序号",
    type: "index",
    headerAlign: "center",
    alignText: "center",
    width: pxToRem(70),
  },
  {
    label: "重要程度",
    prop: "important",
    headerAlign: "center",
    alignText: "center",
    width: pxToRem(150),
  },
  {
    label: "任务层级",
    prop: "workImp",
    alignText: "center",
    headerAlign: "center",
    width: pxToRem(180),
  },
  {
    label: "事项名称",
    prop: "thingName",
    // alignText: "center",
    // headerAlign: "center",
    // width: pxToRem(210),
  },
  {
    label: "牵头责任科室",
    prop: "unit",
    alignText: "center",
    headerAlign: "center",
    width: pxToRem(210),
  },
  {
    label: "责任人",
    prop: "unitUser",
    alignText: "center",
    headerAlign: "center",
    width: pxToRem(140),
  },
  {
    label: "责任领导",
    prop: "unitLeader",
    alignText: "center",
    headerAlign: "center",
    width: pxToRem(140),
    // sort: true,
  },
  {
    label: "完成状态",
    prop: "status",
    alignText: "center",
    headerAlign: "center",
    width: pxToRem(190),
  },
  {
    label: "(计划)完成时间",
    prop: "planTime",
    alignText: "center",
    headerAlign: "center",
    width: pxToRem(180),
    sort: true,
  },
];

export const tableData = ref([]);
export const freedData = [
  {
    id: 1,
    important: "重要且紧急",
    workImp: "各二级行",
    thingName: "制定下发广西区分行2024年监管统计制度",
    unit: "信息统计科",
    unitUser: "黄宁",
    unitLeader: "谭伟明",
    status: "已完成",
    workProcess: "",
    planTime: "2024-04-25",
  },
  {
    id: 2,
    important: "一般且紧急",
    workImp: "分行部门",
    thingName: "制定下发广西分行主要经营数据通报管理规程",
    unit: "信息统计科",
    unitUser: "黄宁",
    unitLeader: "谭伟明",
    status: "已完成",
    workProcess: "",
    planTime: "2024-04-29",
  },
  {
    id: 3,
    important: "重要且紧急",
    workImp: "分行行领导",
    thingName: "广西区分行2024年数据治理工作指引制定",
    unit: "信息统计科",
    unitUser: "黄宁",
    unitLeader: "谭伟明",
    status: "处理中",
    workProcess: "",
    planTime: "2024-05-20",
  },
  {
    id: 4,
    important: "重要且不紧急",
    workImp: "总行/监管",
    thingName: "上报人民银行征信维权创新试点工作方案",
    unit: "信息统计科",
    unitUser: "黄宁",
    unitLeader: "谭伟明",
    status: "处理中",
    workProcess: "",
    planTime: "2024-05-31",
  },
  {
    id: 5,
    important: "重要且不紧急",
    workImp: "金融科技部",
    thingName: "2024年数字化与创新能力提升班",
    unit: "金融科技部",
    unitUser: "曾繁璞",
    unitLeader: "贾志国",
    status: "处理中",
    workProcess: "",
    planTime: "2024-10-25",
  },
  {
    id: 6,
    important: "重要且不紧急",
    workImp: "金融科技部",
    thingName: "网点网络灾备演练",
    unit: "金融科技部",
    unitUser: "李漓",
    unitLeader: "贾志国",
    status: "处理中",
    workProcess: "项目准备：环境测试、配置核查、与渠道部沟通相关事宜",
    planTime: "2024-11-01",
  },
  {
    id: 7,
    important: "重要且不紧急",
    workImp: "金融科技部",
    thingName: "机房内部改造",
    unit: "金融科技部",
    unitUser: "王路",
    unitLeader: "贾志国",
    status: "处理中",
    workProcess: "",
    planTime: "2024-11-30",
  },
  {
    id: 8,
    important: "重要且紧急",
    workImp: "总行/监管",
    thingName: "IT资产数据清理",
    unit: "金融科技部",
    unitUser: "王路",
    unitLeader: "贾志国",
    status: "处理中",
    workProcess: "",
    planTime: "2024-11-30",
  },
  {
    id: 9,
    important: "重要且紧急",
    workImp: "金融科技部",
    thingName: "IT设备采购",
    unit: "金融科技部",
    unitUser: "王路",
    unitLeader: "贾志国",
    status: "处理中",
    workProcess: "",
    planTime: "2024-11-30",
  },
  {
    id: 10,
    important: "重要且不紧急",
    workImp: "分行部门",
    thingName: "2024年产品与创新计划推进",
    unit: "金融科技部",
    unitUser: "曾繁璞",
    unitLeader: "贾志国",
    status: "处理中",
    workProcess: "",
    planTime: "2024-11-30",
  },
  {
    id: 11,
    important: "重要且不紧急",
    workImp: "金融科技部",
    thingName: "中心机房监控值守及巡检服务采购",
    unit: "金融科技部",
    unitUser: "王路",
    unitLeader: "贾志国",
    status: "处理中",
    workProcess: "",
    planTime: "2024-12-15",
  },
  {
    id: 12,
    important: "重要且不紧急",
    workImp: "金融科技部",
    thingName: "基础设施及机房环境维保采购",
    unit: "金融科技部",
    unitUser: "王路",
    unitLeader: "贾志国",
    status: "处理中",
    workProcess: "",
    planTime: "2024-12-15",
  },
  {
    id: 13,
    important: "重要且紧急",
    workImp: "金融科技部",
    thingName: "全区动环监控系统实施",
    unit: "金融科技部",
    unitUser: "王路",
    unitLeader: "贾志国",
    status: "处理中",
    workProcess: "",
    planTime: "2024-12-31",
  },
  {
    id: 14,
    important: "重要且紧急",
    workImp: "各二级行",
    thingName: "全区IT资产设备报废工作",
    unit: "金融科技部",
    unitUser: "王路",
    unitLeader: "贾志国",
    status: "处理中",
    workProcess: "",
    planTime: "2024-12-31",
  },
  // {
  //   id: 15,
  //   important: "重要且不紧急",
  //   workImp: "总行/监管",
  //   thingName: "非金系统数据治理",
  //   unit: "广西区分行",
  //   unitUser: "黄秋燕",
  //   unitLeader: "贾志国",
  //   status: "已办结",
  //   workProcess: "已向总行反馈联系人信息",
  //   planTime: "2024-03-28",
  // },
  {
    id: 16,
    important: "重要且不紧急",
    workImp: "分行部门",
    thingName: "首季需求征集活动分析结果反馈",
    unit: "需求统筹科",
    unitUser: "唐莹",
    unitLeader: "文智勇",
    status: "已办结",
    workProcess: "已形成初步需求分析结果报告",
    planTime: "2024-02-29",
  },
  {
    id: 17,
    important: "重要且不紧急",
    workImp: "各科室",
    thingName: "迈普交换机网点试点",
    unit: "网络管理科",
    unitUser: "凌振盛",
    unitLeader: "李漓",
    status: "已办结",
    workProcess: "已完成配置标准化，由网点进行测试。",
    planTime: "2024-03-31",
  },
  {
    id: 18,
    important: "重要且不紧急",
    workImp: "总行/监管",
    thingName: "服务器漏洞扫描",
    unit: "安全合规科",
    unitUser: "王路",
    unitLeader: "文智勇",
    status: "已办结",
    workProcess: "已完成部分服务器漏洞扫描",
    planTime: "2024-04-26",
  },
  {
    id: 19,
    important: "重要且紧急",
    workImp: "总行/监管",
    thingName: "个人客户信息风险易发领域专项排查",
    unit: "安全合规科",
    unitUser: "冯子夏",
    unitLeader: "文智勇",
    status: "强制办结",
    workProcess: "",
    planTime: "2024-04-29",
  },
  {
    id: 20,
    important: "重要且紧急",
    workImp: "总行/监管",
    thingName: "报送2024年技术能力复用基线",
    unit: "应用开发科",
    unitUser: "陈慧婷",
    unitLeader: "文智勇",
    status: "强制办结",
    workProcess: "梳理中",
    planTime: "2024-04-30",
  },
  {
    id: 21,
    important: "一般且不紧急",
    workImp: "金融科技部",
    thingName: "事项梳理",
    unit: "应用开发科",
    unitUser: "陈慧婷",
    unitLeader: "文智勇",
    status: "已办结",
    workProcess: "",
    planTime: "2024-04-30",
  },
  {
    id: 22,
    important: "重要且不紧急",
    workImp: "总行/监管",
    thingName: "重点需求梳理填报",
    unit: "需求统筹科",
    unitUser: "唐莹",
    unitLeader: "文智勇",
    status: "强制办结",
    workProcess: "需求筛选中",
    planTime: "2024-04-30",
  },
  {
    id: 23,
    important: "重要且紧急",
    workImp: "总行/监管",
    thingName: "对公业务主机下移",
    unit: "系统运行科",
    unitUser: "文辉",
    unitLeader: "文智勇",
    status: "强制办结",
    workProcess: "下移切换工作完成，重保期任务完成，进入最后收官。",
    planTime: "2024-05-01",
  },
  {
    id: 24,
    important: "重要且不紧急",
    workImp: "总行/监管",
    thingName: "SOM系统口令上收",
    unit: "安全合规科",
    unitUser: "王路",
    unitLeader: "文智勇",
    status: "强制办结",
    workProcess: "完成系统上收口令模板的配置。",
    planTime: "2024-05-01",
  },
  {
    id: 25,
    important: "重要且紧急",
    workImp: "总行/监管",
    thingName: "商用密码应用安全性评估",
    unit: "安全合规科",
    unitUser: "秦登高",
    unitLeader: "文智勇",
    status: "强制办结",
    workProcess: "",
    planTime: "2024-07-31",
  },
];

/**
 * px2rem   1920px为基准点
 */
function pxToRem(num, baseWidth = 19.2) {
  if (!num) return "";
  // const baseNum=baseWidth?? 19.2
  return num / baseWidth + "rem";
}
